### ISSUE TITLE
Switch to nw.js?

### ISSUE THREAD

**Issue by Yxi1d** [raluvy95/FelidaBrowser#18]
Switching to nw.js will probably have performance boosts though nw.js is better for web apps rather web browsers

edit; it's probably better to actually work with Tauri than Electron.js because tauri is proven to be better than electron in performance and speeds.

**Comment by Yxi1d** [comment]
I'm working on fixing the tabs so the add tab is actually on the tabs and not on the context bar

**Comment by raluvy95** [comment]
Thank you for suggestion! However, I have tried dfifferent framework like neutralino.js, but they are more optimized for web apps rather than a mini browser. Tauri is a Rust library, so it requires to have Rust knowledge.
