### ISSUE TITLE
Can't login into Google Account

### ISSUE THREAD

**Issue by MsMaciek123** [raluvy95/FelidaBrowser#2]
I don't know if it's problem with ur browser, but when i'm trying to login into my google account on youtube website it says:

![obraz](https://user-images.githubusercontent.com/62432088/85835085-c0729900-b794-11ea-9bde-36300be4554f.png)
![obraz](https://user-images.githubusercontent.com/62432088/85835107-c8323d80-b794-11ea-8157-3d189b4652fa.png)

**Comment by raluvy95** [comment]
It's because Google didn't verify our browser, we don't know how to verify by Google.

**Comment by AtieP** [comment]
Isn't there an easy way to modify the headers?

**Comment by raluvy95** [comment]
well, I found the solution which is called user agent, but because of broken settings (wanted to add custom user agent in advanced settings)... I don't know how to fix settings too.

**Comment by raluvy95** [comment]
The issue has been fixed in v1
